name: publish-gitbook
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on : ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          ref: master

      - name: install node.js
          run :|
            npm install gitbook-cli -g
            npm gitbook -v
